version: '3.9'
services:
  db:
    image: postgres:15
    container_name: locadora-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - locadora-net

  api:
    image: kleberlz7/api-locadora:1.0.2
    container_name: locadora-api
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
    networks:
      - locadora-net

networks:
  locadora-net: