name: CI/CD - Build, Test and Deploy with Versioning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: 1.0.2

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U testuser && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven (using profile ci)
        env:
          CI_DB_USER: ${{ secrets.CI_DB_USER }}
          CI_DB_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        run: mvn clean package -DskipTests=false -Dspring.profiles.active=ci

      - name: Rename JAR (padronizar para CD)
        run: mv target/*.jar app.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: app.jar

  deploy:
    name: Deploy Docker Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=kleberlz7/api-locadora
          VERSION=${{ env.VERSION }}
          docker build -t $IMAGE_NAME:latest \
                       -t $IMAGE_NAME:$VERSION \
                       -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=kleberlz7/api-locadora
          VERSION=${{ env.VERSION }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:${{ github.sha }}

